CYB-466 new base image; cmake scripts refacroting
* new base image now contains: node installed in /root/, eosio.cdt deb
  package build from eosio.cdt-patched git repo, some node sources (e.g.
  wasm files needed for tester initialization);

* daobet.contracts now use daobet-utils.cmake for storing various utils,
  installed via `make install` from dabet node sources into
  $eos_root/lib/cmake/daobet;

* some other paths are set up explicitly in cicd/build.sh;

* CONTRACTS_VERSION (in ontracts.version.hpp.in) is now verified to be
  set up in cmake scripts.

diff --git a/cicd/run b/cicd/run
--- a/cicd/run
+++ b/cicd/run
@@ -1,47 +1,16 @@
-#!/usr/bin/env bash
-set -e
+#!/bin/bash
 
-JOB=$1
+set -eux
 
-# build
-function build(){
-  docker run \
-    --rm \
-    -v `pwd`:/haya/contracts \
-    -w /haya/contracts \
-    -ti mixbytes/haya:devel-patched-cdt \
-    ./cicd/build.sh
-}
+RUN_NODE_WITH_CDT_CMD="docker run --rm -v "$PWD":/daobet.contracts -w /daobet.contracts -ti daobot/daobet:node-with-cdt"
 
-# pack
-function pack(){
-  docker run \
-    --rm \
-    -v `pwd`:/haya/contracts \
-    -w /haya/contracts \
-    -ti mixbytes/haya:devel-patched-cdt \
-    ./cicd/pack.sh
-}
-
-# login
-function login(){
-  docker run \
-    --rm \
-    -v `pwd`:/haya/contracts \
-    -w /haya/contracts \
-    -ti mixbytes/haya:devel-patched-cdt \
-    bash
-}
-
-function test(){
-# test
-  docker run \
-    --rm \
-    -v `pwd`:/haya/contracts \
-    -w /haya/contracts \
-    -ti mixbytes/haya:devel-patched-cdt \
-    /haya/contracts/build/tests/unit_test $@
-}
-
+cmd="${1:?}"
 shift
-$JOB $@
+
+case "$cmd" in
+(build) eval "$RUN_NODE_WITH_CDT_CMD" ./cicd/build.sh ;;
+(test)  eval "$RUN_NODE_WITH_CDT_CMD" ./build/tests/unit_test "$@" ;;
+(pack)  eval "$RUN_NODE_WITH_CDT_CMD" ./cicd/pack.sh ;;
+(login) eval "$RUN_NODE_WITH_CDT_CMD" bash ;;
+(*)     echo >&2 "Invalid command: $cmd." ; exit 1 ;;
+esac
